### ISSUE TITLE
Basic control structure

### ISSUE THREAD

**Issue by zam264** [zam264/HomeAutomation#1]
We need basic switches to control the various pins on the device.

On/Off switches should suffice.

**Comment by mobotus** [comment]
/home/cpsc488/README

Function: hardware
	Usage ./hardware case#
	Main returns 0 for fail.
	Except case 10 which returns an int based on the ambient sound level
		and case 13 that returns temp.
Case:
	3,1,2,5 Control Lights
	4 Control Cooling
	10 Read ambient sound level
	29 Read motion
	12 Switch Status
	13 Read Temperature
	15 Control Heating
	16 Control Fan
	50 Emergency Off
	51 All Lights Off
	52 All Lights On	

The lighting, heating, cooling, and fan are currently programmed as toggles same case can trigger on/off. Thoughts on coding on cases and separate off cases instead of toggles?

**Comment by WBotzer** [comment]
If the PHP scripts can read the state of the switch, then they can call the script with the pin number and the state to set the switch. From there the PHP could determine whether or not to call the actual script to toggle the switch.

**Comment by mobotus** [comment]
I have a status script to build that returns the state of each pin could you make use of that?

**Comment by WBotzer** [comment]
Yea that should work, I'll just need to know what exactly your script takes and what it returns.

**Comment by mobotus** [comment]
Updated script on server "pinio" updated README to reflect usage.
