### ISSUE TITLE
Communicate with device

### ISSUE THREAD

**Issue by zam264** [zam264/HomeAutomation#2]
We need to develop a stable means of communication to the device via PHP/Python scripts.

We should be able to enable/disable pins on the device.

**Comment by WBotzer** [comment]
Corona Labs has a nice library for this so this should be a relatively easy issue.
http://docs.coronalabs.com/api/library/network/request.html

**Comment by zam264** [comment]
Basic communication has been implemented using togglePin.php

All pins can now be toggled on/off with your phone!
